---
- name: Install plexmediaserver
  become: true
  tags:
    - plex
    - plexmediaserver
  block:
  - name: Install python3-debian
    apt:
      name: python3-debian
      update_cache: true
  - name: Install repo
    deb822_repository:
      name: plexmediaserver
      types: deb
      uris:
        - https://downloads.plex.tv/repo/deb
      suites:
        - public
      components:
        - main
      signed_by: https://downloads.plex.tv/plex-keys/PlexSign.key
  - name: Install plexmediaserver
    apt:
      name: plexmediaserver
      update_cache: true
  - name: Instruct Plex to use syslog for logging
    tags:
      - syslog
      - logging
    block:
      - name: Create plexmediaserver.service.d directory
        file:
          path: /etc/systemd/system/plexmediaserver.service.d/
          state: directory
          owner: root
          group: root
          mode: '0755'
      - name: Create override file
        copy:
          content: |
            [Service]
            Environment="PLEX_MEDIA_SERVER_USE_SYSLOG=true"
          dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
          owner: root
          group: root
          mode: '0644'
        notify:
          - Reload systemd
          - Restart plexmediaserver
  - name: Configure service
    service:
      name: plexmediaserver
      state: "{{ plexmediaserver_service_state }}"
      enabled: "{{ plexmediaserver_service_enabled }}"
  - name: Add plex user to groups
    user:
      name: plex
      groups: "{{ plexmediaserver_user_groups }}"
      append: true
    when: plexmediaserver_user_groups | length > 0
    notify: Restart plexmediaserver
