---
- name: Install plexmediaserver
  become: true
  tags:
    - plex
    - plexmediaserver
  block:
  - name: Add apt key
    get_url:
      url: https://downloads.plex.tv/plex-keys/PlexSign.key
      dest: /usr/share/keyrings/plexmediaserver.gpg
      mode: '0644'
      force: true # Download new versions when they are available
  - name: Get architecture
    command: dpkg --print-architecture
    register: deb_architecture
    changed_when: false
  - name: Install repo
    apt_repository:
      repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/plexmediaserver.gpg] https://downloads.plex.tv/repo/deb/ public main"
      state: present
      filename: plexmediaserver
      update_cache: true
  - name: Install plexmediaserver
    apt:
      name: plexmediaserver
  - name: Instruct Plex to use syslog for logging
    tags:
      - syslog
      - logging
    block:
      - name: Create plexmediaserver.service.d directory
        file:
          path: /etc/systemd/system/plexmediaserver.service.d/
          state: directory
          owner: root
          group: root
          mode: '0755'
      - name: Create override file
        copy:
          content: |
            [Service]
            Environment="PLEX_MEDIA_SERVER_USE_SYSLOG=true"
          dest: /etc/systemd/system/plexmediaserver.service.d/override.conf
          owner: root
          group: root
          mode: '0644'
        notify:
          - Reload systemd
          - Restart plexmediaserver
  - name: Configure service
    service:
      name: plexmediaserver
      state: "{{ plexmediaserver_service_state }}"
      enabled: "{{ plexmediaserver_service_enabled }}"
  - name: Add plex user to groups
    user:
      name: plex
      groups: "{{ plexmediaserver_user_groups }}"
      append: true
    when: plexmediaserver_user_groups | length > 0
    notify: Restart plexmediaserver
