---
name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint-action@v6

  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # If tests fail in one image, we still want the others to carry on running
      matrix:
        image:
          - geerlingguy/docker-debian12-ansible # bookworm (stable)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run molecule
        uses: gofrolist/molecule-action@v2
        env:
          IMAGE: ${{ matrix.image }}
